### ISSUE TITLE
No project description

### ISSUE THREAD

**Issue by ArsenShnurkov** [d-aguilera/ProjectReferencesConverter#1]
How you project is different from 
https://github.com/jstangroome/NuGetReferenceHintPathRewrite
?

**Comment by d-aguilera** [comment]
Wow, I didn't notice your comment until now, I'm so sorry @ArsenShnurkov.

If you're still interested, this project was conceived to solve a rather particular problem I'm facing with a massive .NET solution that has so many projects that it is actually continuously built using not one, but several smaller solution files. And projects within this gigantic solution do not reference each other as project files, but rather as assemblies. While this helps dividing the solution into smaller sub-solutions, it's a real pain when it comes to debugging.
So I wrote this extension that automatically converts all assembly references in current solution into project references. In order to do so, it searches a given directory for project files and automatically adds missing referenced projects to current solution.

**Comment by ArsenShnurkov** [comment]
thanks
